---
- name: uninstall glusterfs
  block:
    - include: glusterfs_config_facts.yml
    - include: glusterfs_uninstall.yml
  when: "'glusterfs' in groups and groups['glusterfs'] | length > 0"

- name: uninstall glusterfs registry
  block:
    - include: glusterfs_registry_facts.yml
    - include: glusterfs_uninstall.yml
  when: "'glusterfs_registry' in groups and groups['glusterfs_registry'] | length > 0"
